-- ============================================================
-- Cleanup: Remove all fake prices from product_catalog
-- These were generated by the old scrape-all.mjs using 
-- BRAND_PRICE_KNOWLEDGE fallbacks, NOT real scraped prices.
-- ============================================================

-- 1. NULL out fake retail_price, currency, source_url on all products
--    that came from the scraper sources (obf, amazon_de, etc.)
UPDATE product_catalog
SET 
  retail_price = NULL,
  currency = NULL,
  source_url = NULL
WHERE source IN ('obf', 'amazon_de', 'open_beauty_facts', 'amazon', 'scraper');

-- 2. Also NULL out any product where retail_price matches
--    known fake brand-level prices from BRAND_PRICE_KNOWLEDGE
UPDATE product_catalog
SET 
  retail_price = NULL,
  currency = NULL,
  source_url = NULL
WHERE retail_price IS NOT NULL 
  AND retail_price::numeric IN (
    8.00, 12.00, 14.00, 15.00, 16.00, 18.00, 20.00, 21.99, 
    22.00, 23.99, 24.99, 25.00, 28.00, 30.00, 32.00, 35.00, 
    38.00, 40.00, 42.00, 45.00, 48.00, 50.00, 55.00, 60.00, 
    65.00, 70.00, 75.00, 80.00, 85.00, 90.00, 95.00, 100.00, 
    110.00, 120.00, 150.00
  );

-- 3. Truncate scrape_staging (all data is fake)
TRUNCATE TABLE scrape_staging;
